{
  "type": "record",
  "name": "AuthUserCreatedEventPayload",
  "namespace": "kafkacontracts.auth",
  "fields": [
    {
      "name": "authUserId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "email",
      "type": "string"
    },
    {
      "name": "firstName",
      "type": "string"
    },
    {
      "name": "lastName",
      "type": "string"
    },
    {
      "name": "verificationCode",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "role",
      "type": "string"
    }
  ]
}
